-- Password hash below should be replaced with one generated by bcrypt in your environment.
insert into crm_users (role,email,username,passcode_hash)
values
('manager','manager@cashclosers.local','manager','$2a$10$8fIYt1P6fPJbfYhNlsfXz.OZsqjCiApeSI8A90.wVQ4ryTJ5uhmg2'),
('agent','agent1@cashclosers.local','agent1','$2a$10$8fIYt1P6fPJbfYhNlsfXz.OZsqjCiApeSI8A90.wVQ4ryTJ5uhmg2')
on conflict do nothing;

insert into crm_accounts (name,industry) values ('BizyDepo','Marketplace') on conflict do nothing;

with p as (
  insert into crm_pipelines(name) values ('Global Sales Pipeline') returning id
)
insert into crm_pipeline_stages (pipeline_id,name,sort_order)
select p.id, s.name, s.sort_order from p cross join (values
('New Lead',1),('Contacted',2),('Interested',3),('Follow-up',4),('Proposal Sent',5),('Closed Won',6),('Closed Lost',7)
) as s(name, sort_order);
